### ISSUE TITLE
There was a critical exception handling a packet on channel austinv11CF java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Xiaminou** [rolandoislas/TheFramework#1]
This is an error that I found in the logs after my client got disconnected, seemingly out of nowhere, from my server.

Logs: [fml-junk-earlystartup.txt](https://github.com/rolandoislas/TheFramework/files/1560470/fml-junk-earlystartup.txt) (Line 78381)

Minecraft: 1.12.2
Forge: 2562
Mods: [list.txt](https://github.com/rolandoislas/TheFramework/files/1560472/list.txt)

**Comment by Xiaminou** [comment]
I think I know what triggered it, looks like TFW binds F9 to something, I was pressing F9 for the Light Level Overlay. However it still shouldn't have crashed, but I see that you fixed that, thanks.

**Comment by Xiaminou** [comment]
https://pastebin.com/bCTeuZkm
Is this a new error or the same?

**Comment by opencma** [comment]
It is the same one. Does it happen every time when pressing F9?

Edit: I found the problem.
Edit 2: No, I did not.

**Comment by Xiaminou** [comment]
No this time it happened when my client tried to connect to the server and got disconnected immediately, I don't know for sure that this was the problem but it's the only error I could find around the time I connected.
I ended up removing The Framework from my mods.

**Comment by Kevadroz** [comment]
Still happens:

[Singleplayer world load](https://hastebin.com/raw/ixuvavuraj)

**Comment by Dalethium** [comment]
Check out #7 I sent a fix.
