### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by JoeSGT** [rolandoislas/TheFramework#2]
Hello i am experience this crash report from your mod,
all versions and mod's that i am using it's in the crash report 
https://pastebin.com/nqmxiRRp

**Comment by JoeSGT** [comment]
When i update the framework to 1.12.2-1.0.1-build-T20 and my console spam this
https://pastebin.com/YeqQWXc7

**Comment by opencma** [comment]
That is debug logging. While it does log an error, it should not affect the game. The next build fixes it.

**Comment by JoeSGT** [comment]
Thanks you for fixing that but it seem still having that same crash https://pastebin.com/8iNy21yu using TheFramework-1.12.2-1.0.1-build-T20

**Comment by opencma** [comment]
I forgot to mention that the bug is from PeripheralsPlusOne. Version [1.1](https://github.com/rolandoislas/PeripheralsPlusOne/releases) has a fix.

**Comment by JoeSGT** [comment]
i have seen that you said curseforge took it down, have you contacted them to get it resolve ?

**Comment by opencma** [comment]
I have sent a ticket, but I do not know when they will get around to it or if they will manually approve it.

**Comment by opencma** [comment]
The latest build is now on CurseForge.

**Comment by JoeSGT** [comment]
Thanks you for everything
